sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
 - pip install -U pip wheel setuptools
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt
script:
 - python -m unittest2.__main__ discover
